version: '3.8'

services:
  bot:
    build:
      context: .
    container_name: docker-testing
    ports:
      - "8080:8080"
    volumes:
      - docker-testing-data:/usr/src/app/data
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  docker-testing-data:
  redis-data:
