name: CI/CD Docker Bot

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@195.133.25.229 << 'EOF'
        # Остановить и удалить старый контейнер, если он существует
        docker stop docker-testing || true
        docker rm docker-testing || true

        # Пересобрать образ
        cd /root/docker-tesing
        git pull
        docker build -t docker-testing .

        # Убедиться, что volume для базы данных существует
        docker volume create docker-testing-data

        # Запустить контейнер с подключением volume
        docker run -d --name docker-testing -p 8080:8080 -v docker-testing-data:/usr/src/app/data docker-testing
        EOF
